allowed:
  origins:
    https://svangerskapspengesoknad.dev.nav.no,
    https://engangsstonad.dev.nav.no,
    https://foreldrepengeplanlegger.dev.nav.no,
    https://foreldrepengesoknad.dev.nav.no,
    https://foreldrepengesoknad-rework.dev.nav.no,
    https://foreldrepenger.dev.nav.no,
    https://foreldrepengesoknad.ekstern.dev.nav.no

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  mvc:
    log-request-details: true

virus:
  uri: http://clamav.clamav/scan

no.nav:
  security:
    jwt:
      client:
        registration:
          ncat-logger:
            well-known-url: ${token.x.well.known.url}
            grant-type: urn:ietf:params:oauth:grant-type:token-exchange
            authentication:
              client-id: ${token.x.client.id}
              client-jwk: ${token.x.private.jwk}
              client-auth-method: private_key_jwt
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
          fpsoknad-mottak:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpsoknad-mottak
          fpinfo-historikk:
            token-exchange:
              audience: dev-fss:teamforeldrepenger:fpinfo-historikk
      issuer:
        selvbetjening:
          discoveryurl: https://navtestb2c.b2clogin.com/navtestb2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten_ver1
          accepted_audience: 9ecf7c8f-4efd-466d-b864-97fe3571b160
          cookie_name: selvbetjening-idtoken

oppslag:
  uri: http://ncat-logger.nais.svc.cluster.local
historikk:
  uri: https://fpinfo-historikk.dev-fss-pub.nais.io/api/
mottak:
  uri: http://ncat-logger.nais.svc.cluster.local
innsyn:
  uri: http://ncat-logger.nais.svc.cluster.local
minidialog:
  uri: https://fpinfo-historikk.dev-fss-pub.nais.io/api/
fppdfgen:
  uri: http://fppdfgen
